In [ ]:
# univariate lstm
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Temperature.csv")

In [ ]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
 X, y = list(), list()
 for i in range(len(sequence)):
 # find the end of this pattern
  end_ix = i + n_steps
  # check if we are beyond the sequence
  if end_ix > len(sequence)-1:
    break
 # gather input and output parts of the pattern
  seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
  X.append(seq_x)
  y.append(seq_y)
 return array(X), array(y)

In [ ]:
# define input sequence
#raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(df['MaxTemp'], n_steps)


In [ ]:
# summarize the data
for i in range(len(X)):
 print(X[i], y[i])

[24.3 26.9 23.4] 15.5
[26.9 23.4 15.5] 16.1
[23.4 15.5 16.1] 16.9
[15.5 16.1 16.9] 18.2
[16.1 16.9 18.2] 17.0
[16.9 18.2 17. ] 19.5
[18.2 17.  19.5] 22.8
[17.  19.5 22.8] 25.2
[19.5 22.8 25.2] 27.3
[22.8 25.2 27.3] 27.9
[25.2 27.3 27.9] 30.9
[27.3 27.9 30.9] 31.2
[27.9 30.9 31.2] 32.1
[30.9 31.2 32.1] 31.2
[31.2 32.1 31.2] 30.0
[32.1 31.2 30. ] 32.3
[31.2 30.  32.3] 33.4
[30.  32.3 33.4] 33.4
[32.3 33.4 33.4] 19.4
[33.4 33.4 19.4] 18.5
[33.4 19.4 18.5] 24.3
[19.4 18.5 24.3] 28.4
[18.5 24.3 28.4] 26.9
[24.3 28.4 26.9] 22.2
[28.4 26.9 22.2] 28.0
[26.9 22.2 28. ] 24.3
[22.2 28.  24.3] 24.1
[28.  24.3 24.1] 20.4
[24.3 24.1 20.4] 26.3
[24.1 20.4 26.3] 24.2
[20.4 26.3 24.2] 26.5
[26.3 24.2 26.5] 21.8
[24.2 26.5 21.8] 26.8
[26.5 21.8 26.8] 25.8
[21.8 26.8 25.8] 28.2
[26.8 25.8 28.2] 29.4
[25.8 28.2 29.4] 24.8
[28.2 29.4 24.8] 18.5
[29.4 24.8 18.5] 21.5
[24.8 18.5 21.5] 20.3
[18.5 21.5 20.3] 27.1
[21.5 20.3 27.1] 29.9
[20.3 27.1 29.9] 21.1
[27.1 29.9 21.1] 21.7
[29.9 21.1 21.7] 20.9
[21.1 21.7

In [ ]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [ ]:
n_features

1

In [ ]:
X.shape[1]

3

In [ ]:
X.shape[0]

353

In [ ]:
# define model

#This initializes a Keras Sequential model, which is a linear stack of layers
#Adds an LSTM layer with 50 units (neurons)
#activation='relu' ReLU (Rectified Linear Unit) is a common activation function that helps introduce non-linearity into the model.
#input_shape=(n_steps, n_features): Specifies the shape of the input data

model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [ ]:
# fit model
model.fit(X, y, epochs=200, verbose=0)

In [ ]:
# demonstrate prediction
x_input = array([28.5,27.4,20.6])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[21.226912]]
